
version: "3.5"

services:
  shiny:
      restart: always
      deploy:
          resources:
              limits:
                  cpus: "1.25"
                  memory: 2.0G
                  #cpus: "3.00"
                  #memory: 4.0G
