#!/bin/bash

set -u

container_name="shiny_shiny"

n=`docker ps | egrep "${container_name}" | wc -l`
if [ $n -eq 0 ] ; then
    printf "Container \"%s\" seems not to run.\n" ${container_name}
elif [ $n -lt 1 ] ; then
    printf "Found multiple containers \"%s\".\n" ${container_name}
else
    container_id=`docker ps | egrep "${container_name}" | awk '{print $1}'`
    printf "Found container with id \"%s\"\n" ${container_id}
    docker exec -it ${container_id} /bin/bash
fi

